public class EyeGlass {

    private String shape;
    private String color;
    private String colorlense;
    private String type;
    private String material;
    private String status;
    
public EyeGlass(String shape, String color, String colorlense, String type, String material, String status) {
    super();
    this.shape =shape;
    this.color =color;
    this.colorlense =colorlense;
    this.type =type;
    this.material =material;
    this.status ="Off Glass";
}
    
    public EyeGlass() {
        super();
        this.status = "Off Eye Glass";
    }

    public String getShape() {
        return shape;
    }
    public void setShape(String shape){
        this.shape = shape;
    }

    public String getColor() {
        return color;
    }
    public void setColor(String color){
        this.color = color;
    }
    
    public String getColorLense() {
        return colorlense;
    }
    public void setColorLense(String colorlense){
        this.colorlense = colorlense;
    }

    public String getType() {
        return type;
    }
    public void setType(String type){
        this.type = type;
    }

    public String getMaterial() {
        return material;
    }
    public void setMaterial(String material){
        this.material = material;
    }

    public void PutOnEyeGlass() {
        this.status = "Glass On";
    }
    public void PutOffEyeGlass() {
        this.status = "Glass Off";
    }
    public String getStatus() {
        return status;
    }
    
    public void UsedOnSunnyDays() {
        this.colorlense = "Dark Black";
    }
}
